### ISSUE TITLE
Possible ClassNotFoundException

### ISSUE THREAD

**Issue by Sxtanna** [XZot1K/ZotBox#2]
With your example in the readme, wouldn't you get a CNFE if ZotBox wasn't an installed plugin? 
Maybe I'm missing something here, but I'm not sure..

**Comment by XZot1K** [comment]
If a plugin is using ZotBox as a dependency then yes CNFE will most likely
happen if it's not installed. However, if you build ZotBox directly into
the plugin you will not get CNFEs just you will need to build each version
of ZotBox when a update is released for packets or you could just replace
changed classes!
